apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx-internal
  includeCRDs: true
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx-internal
  version: 4.10.0
  valuesFile: values.yaml

resources:
- base/ingress-nginx-internal-ns.yaml